[package] 
name = "dual_blockchain"
version = "0.1.0"
edition = "2021"
[dependencies]
tokio = { version = "1.0", features = ["full"]}
serde = { version = "1.0", features = ["derive"]}
rand = "0.8"
[[bin]]
name = "dualhelix"
path = "src/main.rs"