[package] 
name = "dualhelix"
version = "0.1.0"
edition = "2021"
[dependencies]
tokio = "1"
serde = "1"
rand = "0.8"
[[bin]]
name = "chain_a"
path = "chain_a/chain_a.rs"
[[bin]]
name = "chain_b"
path = "chain_b/chain_b.rs"